# Generated by Django 5.1 on 2024-08-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warnung', 'Warnung'), ('support', 'Support')], default='info', max_length=10),
        ),
    ]
