# Generated by Django 5.1 on 2024-11-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userstudyprogram_enrollment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
