# Base image: Use a lightweight Node image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
ENV NODE_ENV=development
RUN yarn install

# Copy the remaining code
COPY . .

# Expose port (default port for Vue is 8080)
EXPOSE 8080

# Start command: Launch the development server
CMD ["yarn", "serve"]
