version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
